---
apiVersion: v1
kind: Service
metadata:
  name: event-manager-frontend
spec:
  type: LoadBalancer
  selector:
    app: event-manager-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-manager-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-manager-frontend
  template:
    metadata:
      labels:
        app: event-manager-frontend
    spec:
      containers:
        - name: event-manager-frontend
          image: torbencarstens/event_manager_frontend
          ports:
            - containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: event-manager-frontend-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: event-manager-frontend-config
data:
  ROCKET_ENV: prod
