name: Build/Publish docker image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to Github Packages
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Build the tagged Docker image
        run: docker build -t docker.pkg.github.com/torbencarstens/event-manager-frontend/frontend:${{steps.vars.outputs.tag}}
      - name: Push the tagged Docker image
        run: docker push docker.pkg.github.com/torbencarstens/event-manager-frontend/frontend:${{steps.vars.outputs.tag}}
